// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHV1OiP2sopRddFOpuwQ1l48CDkkr5OFI',
    appId: '1:40617019744:web:b410e85feaf2e220417605',
    messagingSenderId: '40617019744',
    projectId: 'ahnan-study-app',
    authDomain: 'ahnan-study-app.firebaseapp.com',
    storageBucket: 'ahnan-study-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCILN8FCF1CH89aGQ82CG7mSwytkoWSrps',
    appId: '1:40617019744:android:af3ce255f19e8853417605',
    messagingSenderId: '40617019744',
    projectId: 'ahnan-study-app',
    storageBucket: 'ahnan-study-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZCSIM_CXRYOrKttgMKvnlY4VTdUG0GUw',
    appId: '1:40617019744:ios:97d834a3befee8d3417605',
    messagingSenderId: '40617019744',
    projectId: 'ahnan-study-app',
    storageBucket: 'ahnan-study-app.firebasestorage.app',
    iosBundleId: 'com.example.studyTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZCSIM_CXRYOrKttgMKvnlY4VTdUG0GUw',
    appId: '1:40617019744:ios:97d834a3befee8d3417605',
    messagingSenderId: '40617019744',
    projectId: 'ahnan-study-app',
    storageBucket: 'ahnan-study-app.firebasestorage.app',
    iosBundleId: 'com.example.studyTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHV1OiP2sopRddFOpuwQ1l48CDkkr5OFI',
    appId: '1:40617019744:web:6863292a347cd714417605',
    messagingSenderId: '40617019744',
    projectId: 'ahnan-study-app',
    authDomain: 'ahnan-study-app.firebaseapp.com',
    storageBucket: 'ahnan-study-app.firebasestorage.app',
  );
}
